version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_lab04
    environment:
      MYSQL_DATABASE: lab04
      MYSQL_USER: jjh
      MYSQL_PASSWORD: pass
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  db_data: